apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  namespace: dmetzler
  name: green
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: game2048
    spec:
      containers:
        - image: dmetzler/web-color
          imagePullPolicy: Always
          name: color
          ports:
            - containerPort: 80
          env:
           - name: COLOR
             value: "#00ff00"
